### ISSUE TITLE
Digest Error on trying to login through mobile browser

### ISSUE THREAD

**Issue by 0xcharanmadhu** [0xcharanmadhu/xmtp-login-wagmi#2]
![Screenshot (2)](https://github.com/0xcharanmadhu/xmtp-login-wagmi/assets/162513253/daa814fd-f1e9-4b87-b41c-0b1c0a32188a)

Here I tried to get the signature from the wallet. After signing I am getting this error:
Error initializing XMTP: TypeError: Cannot read properties of undefined (reading 'digest')
    at se (index.js:79:4903)
    at ue.signKey (index.js:79:9162)
    at Ce.addPreKey (index.js:79:20774)
    at Ce.generate (index.js:79:20536)
    at async ws.newKeystore (index.js:79:77433)
    at async eval (index.js:79:89169)
    at async Us.create (index.js:79:89095)
    at async Us.getKeys (index.js:79:89527)
    at async handleConnect (page.tsx:24:16)

**Comment by 0xcharanmadhu** [comment]
> ![Screenshot (2)](https://private-user-images.githubusercontent.com/162513253/312263201-daa814fd-f1e9-4b87-b41c-0b1c0a32188a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAyODY1MDgsIm5iZiI6MTcxMDI4NjIwOCwicGF0aCI6Ii8xNjI1MTMyNTMvMzEyMjYzMjAxLWRhYTgxNGZkLWYxZTktNGI4Ny1iNDFjLTBiMWMwYTMyMTg4YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxMlQyMzMwMDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xZGIxNDgyZTEwMDdlMzJlNzExYmY2ZGMzMzEzZGU3MWEzYmIwZWM5MzljYjE5ZGE4ZGMzYTFhZTI1ZmJmM2ZlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.IFFwZf9m7udQu2ItNyoXnyjnO544z6vasXvDyysCFDo)
> 
> Here I tried to get the signature from the wallet. After signing I am getting this error: Error initializing XMTP: TypeError: Cannot read properties of undefined (reading 'digest') at se (index.js:79:4903) at ue.signKey (index.js:79:9162) at Ce.addPreKey (index.js:79:20774) at Ce.generate (index.js:79:20536) at async ws.newKeystore (index.js:79:77433) at async eval (index.js:79:89169) at async Us.create (index.js:79:89095) at async Us.getKeys (index.js:79:89527) at async handleConnect (page.tsx:24:16)

Note: Everything Works fine in desktop web browser! I am able to initialize xmtp in desktop web browser

**Comment by 0xcharanmadhu** [comment]
![Screenshot (6)](https://github.com/0xcharanmadhu/xmtp-login-wagmi/assets/162513253/123755f7-f31a-4741-b235-ed7393d801a1)

Everything works on deployment! The error is due to next server port forwarding!
